/* Generated By:JavaCC: Do not edit this line. HackvertorParserConstants.java */
package hackvertor.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HackvertorParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDENTIFIER = 4;
  /** RegularExpression Id. */
  int QUOTED_STRING = 5;
  /** RegularExpression Id. */
  int LITERAL = 6;
  /** RegularExpression Id. */
  int WHITESPACE = 7;
  /** RegularExpression Id. */
  int TAG_START = 8;
  /** RegularExpression Id. */
  int ENDTAG_START = 9;
  /** RegularExpression Id. */
  int TEXT = 10;
  /** RegularExpression Id. */
  int LESSTHAN = 11;
  /** RegularExpression Id. */
  int FUNCTION_NAME = 12;
  /** RegularExpression Id. */
  int ST_ERR = 13;
  /** RegularExpression Id. */
  int ARGS_START = 14;
  /** RegularExpression Id. */
  int SELF_CLOSE_TAG_END = 15;
  /** RegularExpression Id. */
  int SELF_CLOSE_TAG_END_AT = 16;
  /** RegularExpression Id. */
  int TAG_END = 17;
  /** RegularExpression Id. */
  int IT_ERR = 18;
  /** RegularExpression Id. */
  int QUOTED_STRING_VAL = 19;
  /** RegularExpression Id. */
  int LITERAL_VAL = 20;
  /** RegularExpression Id. */
  int COMMA = 21;
  /** RegularExpression Id. */
  int ARGS_END = 22;
  /** RegularExpression Id. */
  int ARG_ERR = 23;
  /** RegularExpression Id. */
  int UNKNOWN = 24;

  /** Lexical state. */
  int Args = 0;
  /** Lexical state. */
  int InsideTag = 1;
  /** Lexical state. */
  int StartTag = 2;
  /** Lexical state. */
  int DEFAULT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"=\\r\"",
    "\"=\\r\\n\"",
    "<IDENTIFIER>",
    "<QUOTED_STRING>",
    "<LITERAL>",
    "<WHITESPACE>",
    "\"<@\"",
    "\"<@/\"",
    "<TEXT>",
    "\"<\"",
    "<FUNCTION_NAME>",
    "<ST_ERR>",
    "\"(\"",
    "\"/>\"",
    "\"@/>\"",
    "\">\"",
    "<IT_ERR>",
    "<QUOTED_STRING_VAL>",
    "<LITERAL_VAL>",
    "\",\"",
    "\")\"",
    "<ARG_ERR>",
    "<UNKNOWN>",
  };

}
