/* Generated By:JavaCC: Do not edit this line. HackvertorParserConstants.java */
package burp.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HackvertorParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDENTIFIER = 4;
  /** RegularExpression Id. */
  int QUOTED_STRING = 5;
  /** RegularExpression Id. */
  int LITERAL = 6;
  /** RegularExpression Id. */
  int OPEN_TAG_START = 7;
  /** RegularExpression Id. */
  int END_TAG_START = 8;
  /** RegularExpression Id. */
  int TEXT = 9;
  /** RegularExpression Id. */
  int FUNCTION_NAME = 10;
  /** RegularExpression Id. */
  int ST_ERROR = 11;
  /** RegularExpression Id. */
  int ARGS_START = 12;
  /** RegularExpression Id. */
  int TAG_END = 13;
  /** RegularExpression Id. */
  int QUOTED_STRING_VAL = 14;
  /** RegularExpression Id. */
  int LITERAL_VAL = 15;
  /** RegularExpression Id. */
  int COMMA = 16;
  /** RegularExpression Id. */
  int ARGS_END = 17;
  /** RegularExpression Id. */
  int UNKNOWN = 18;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int Args = 1;
  /** Lexical state. */
  int InsideTag = 2;
  /** Lexical state. */
  int StartTag = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"=\\r\"",
    "\"=\\r\\n\"",
    "<IDENTIFIER>",
    "<QUOTED_STRING>",
    "<LITERAL>",
    "\"<@\"",
    "\"<@/\"",
    "<TEXT>",
    "<FUNCTION_NAME>",
    "<ST_ERROR>",
    "\"(\"",
    "\">\"",
    "<QUOTED_STRING_VAL>",
    "<LITERAL_VAL>",
    "\",\"",
    "\")\"",
    "<UNKNOWN>",
  };

}
